boost:
  - 1.70.0
h5py:
  - 2.10
hdf5:
  - 1.10.5
jpeg:
  - 9b
lemon:
  - 1.3.1
libpng:
  - 1.6.36
libtiff:
  - 4.0.10
numpy:
  - 1.16
python:
  - 3.7

pin_run_as_build:
  boost:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
