package:
  name: ilastik-package
  version: "1.0"

build:
  number: 2

requirements:
  build:
    - git
    - ilastik-dependencies-no-solvers
  run:
    - git
    - ilastik-dependencies-no-solvers

about:
  summary: "A meta-package for creating installers."
