boost:
  - 1.68.0
h5py:
  - 2.9
hdf5:
  - 1.10.4
jpeg:
  - 9b
lemon:
  - 1.2.4
libpng:
  - 1.6.36
libtiff:
  - 4.0.10
numpy:
  - 1.12
python:
  - 3.6

pin_run_as_build:
  boost: x.x
  h5py: x.x
  hdf5: x.x.x
  jpeg: x.x
  lemon: x.x.x
  libpng: x.x
  libtiff: x.x.x
  numpy: x.x
  python: x.x
