package:
  name: vigra

  # Transform tag:
  # Version-1-11-0 --> 1.11.0
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("Version-","")|replace("-", ".") %}

  # If we're using a non-tagged revision, append '.postN' to the version
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}

  version: {{tagged_version}}

source:
  git_url: https://github.com/ukoethe/vigra
  git_tag: HEAD

build:
  features:
    - vc14 # [win]
  number: 8
  msvc_compiler: 14.0 # [win]

  #
  # You must build this recipe using 'conda build --numpy=X.Y'
  #
  string: np{{np}}py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

  script_env:
    - VIGRA_SKIP_TESTS
    # Control building with CXX11 abi
    - DO_NOT_BUILD_WITH_CXX11_ABI  # [linux]

requirements:
  build:
    - python 2.7*|3.5*|3.6*
    - python {{PY_VER}}*
    - numpy >=1.9,{{NPY_VER}}*
    - jpeg     9b
    - libtiff  4.0.9
    - libpng   1.6.27
    - fftw     3.3*
    - hdf5     1.10.1
    - h5py     2.7.1
    - boost    1.63.0
    - lemon    1.2.4
    - zlib     1.2*
    - nose

  run:
    - python {{PY_VER}}*
    - numpy  {{NPY_VER}}*
    - jpeg     9*
    - libtiff  4.0.9   # libtiff version must exactly match from the build (on osx, at least)
    - libpng   >=1.6.27,<1.7
    - fftw     3.3*
    - hdf5     1.10.1
    - h5py     2.7.1
    - boost    1.63.0
    - lemon    1.2.4
    # in order to suppor older linux distros after gcc5 switch:
    - libstdcxx-ng >=5.4.0  # [linux]
    - zlib     1.2*
    - nose

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision

