package:
  name: vigra
  version: "1.10"

source:
  git_url: git://github.com/ukoethe/vigra.git
  git_tag: 35e5d4aed380087d75e206348d1648d9ad9cf1e6 # 2015-07-16, must include commit e4946fe0387bf9086ef074da6912c763f832c053

build:
  script_env:
   - LD_LIBRARY_PATH
   - DYLD_LIBRARY_PATH

  number: 9
  string: 9_35e5d4a
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc 4.8.2.99 # [linux]
    - gcc 4.8.2 # [osx]
    - python   2.7*
    - numpy    >=1.9
    - jpeg     8d
    - libtiff  4.0*
    - libpng   1.6.17
    - fftw     3.3*
    - hdf5     1.8.14
    - boost    1.55.0
    - zlib     1.2*
    - nose

  run:
    - libgcc   4.8*
    - python   2.7*
    - numpy    >=1.9
    - jpeg     8d
    - libtiff  4.0*
    - libpng   1.6.17
    - fftw     3.3*
    - hdf5     1.8.14
    - boost    1.55.0
    - zlib     1.2*
    - nose

test:
  imports:
    - vigra

about:
  home: http://ukoethe.github.io/vigra
  license: MIT
  summary: Generic Programming for Computer Vision

