package:
  name: altgraph
  version: "0.14"

source:
  fn: altgraph-0.14.tar.gz
  url: https://pypi.python.org/packages/02/e8/e3e0bef46dc329afec0614d63e3c17fd799e41f8d235e8bd4c3b0175de91/altgraph-0.14.tar.gz
  md5: 30cbbc835a64ca3fa0eec41fc6ff936f
#  patches:
   # List any patch files here
   # - fix.patch

  build:
    number: 1000
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - altgraph = altgraph:main
    #
    # Would create an entry point called altgraph that calls altgraph.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - altgraph

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://packages.python.org/altgraph
  license: MIT License
  summary: 'Python graph (network) package'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
