{% set name = "macholib" %}
{% set version = "1.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c4180ffc6f909bf8db6cd81cff4b6f601d575568f4d5dee148c830e9851eb9db

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - altgraph >=0.15
    - pip
    - python
  run:
    - altgraph >=0.15
    - python

test:
  imports:
    - macholib

about:
  home: http://bitbucket.org/ronaldoussoren/macholib
  license: MIT
  license_family: MIT
  summary: Mach-O header analysis and editing
