
package:
  name: lemon
  version: "1.3.1"

source:
  fn: lemon-1.3.1.tar.gz
  url: http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz
  sha256: 71b7c725f4c0b4a8ccb92eb87b208701586cf7a96156ebd821ca3ed855bad3c8

  patches:
  #   - lemon.patch
    - lemon-test.patch
  # the lgf_reader_writer_test fails for some reason. We don't use that format
  # at all or any lemon-based io, so deferring investigation of the exact cause.
    - lemon-lgfrw-test.patch  # [win]
  # Note: switching to the conda compilers introduced a build error with
  # clang 4.0.2:
  #   lemon/path.h:231:24: error: no viable conversion from
  #  'typename PredMapPath<Digraph, NodeMap<Arc> >::RevArcIt' to 'value_type'
  # this patch is similar to the proposition in
  # https://stackoverflow.com/a/33641030
  # and uses the explicit cast operator to Arc.
    - 0001-fix-build-error-with-clang-4.patch  # [osx]
    - lemon-bigobj.patch  # [win]

build:
  number: 1006
requirements:
  build:
    - cmake
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}

about:
  home: http://lemon.cs.elte.hu/trac/lemon
  license: Boost
  summary: Library for Efficient Modeling and Optimization in Networks
