package:
  name: modulegraph
  version: "0.15"

source:
  fn: modulegraph-0.15.tar.gz
  url: https://pypi.python.org/packages/55/4e/67dff18461839a36fd60b2efdc40907f59578c93b9f89fd32024830a8000/modulegraph-0.15.tar.gz
  md5: 453489055c51a76a50d64aa74563d79f
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1000
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - modulegraph = modulegraph:main
    #
    # Would create an entry point called modulegraph that calls modulegraph.main()

    - modulegraph = modulegraph.__main__:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - altgraph >=0.12

  run:
    - python
    - altgraph >=0.12

test:
  # Python imports
  imports:
    - modulegraph

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - modulegraph -m sys

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/ronaldoussoren/modulegraph
  license: MIT License
  summary: 'Python module dependency analysis tool'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
