package:
  name:
    z5py
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}
  version:
   {{tagged_version}}


source:
  path: ..


build:
  number: 0
  string: py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}


requirements:
  build:
    - python {{PY_VER}}*
    - cmake
    - boost-cpp 1.68.0  # the boost version needs to be fixed, because we are linking against specific shared objects
    - xtensor 0.18.1
    - xtensor-python 0.21.0
    - numpy >=1.15
    - nlohmann_json
    - blosc
    - bzip2
    - xz
    - zlib
  run:
    - python {{PY_VER}}*
    - boost-cpp 1.68.0
    - numpy >=1.15
    - six
    - blosc
    - bzip2
    - xz
    - zlib


test:
  imports:
    - z5py
