package:
  name: "ilastik-dependencies-binary"
  version: "0.2"

build:
  number: 0

requirements:
  run:
    - ilastik-dependencies
    - ilastik
    - ilastik-package  # [win]
    - ilastik-exe  # [win]
    - ilastik-launch  # [not win]

about:
  summary: "A meta-package bundling requirements for producing ilastik binaries"
