package:
  name: "ilastik-dependencies-binary"
  version: "0.1"

build:
  number: 1000

requirements:
  run:
    - ilastik-dependencies
    - ilastik-meta
    - ilastik-package  # [win]
    - ilastik-exe  # [win]
    - ilastik-launch  # [not win]

about:
  summary: "A meta-package bundling requirements for producing ilastik binaries"
