about:
  summary: "A meta-package for building all the dependencies needed for only pixel/object classification."

package:
  name: ilastik-deps-pc
  version: "1.1"

build:
  number: 4

requirements:

  run:
    - ilastik-deps-pc-headless
    - pyqt
    - qimage2ndarray
    - futures
    - matplotlib

    # Python was already included via the headless package,
    # but we need to add it explicitly here due to a conda bug.
    - python
    
