{% set name = "py2app" %}
{% set version = "0.19" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3b9f4deb466998304fedea739bfa7bc553a1887656f7ee6accb2899e9e45b52

build:
  number: 0
  entry_points:
    - py2applet = py2app.script_py2applet:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - altgraph >=0.16
    - macholib >=1.11
    - modulegraph >=0.17
    - pip
    - python
    - setuptools
  run:
    - altgraph >=0.16
    - macholib >=1.11
    - modulegraph >=0.17
    - python
    - setuptools

test:
  imports:
    - py2app
    - py2app.apptemplate
    - py2app.bootstrap
    - py2app.bundletemplate
    - py2app.converters
    - py2app.recipes
    - py2app.recipes.PIL
  commands:
    - py2applet --help

about:
  home: http://bitbucket.org/ronaldoussoren/py2app
  license: MIT
  license_family: MIT
  summary: Create standalone Mac OS X applications with Python
