package:
  name: boost
  version: 1.55.0

source:
  fn: boost_1_55_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2

  patches:
    - 1.55.0_patches/6bb71fdd.diff  [osx]
    - 1.55.0_patches/e4bde20f.diff  [osx]
    - 1.55.0_patches/0005-Boost.S11n-include-missing-algorithm.patch  [osx]

build:
  {% set build_num = 5 %}
  number: {{build_num}}
  detect_binary_files_with_prefix: true
  string: py{{CONDA_PY}}_{{build_num}}

requirements:
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - python 2.7*|3.5*
    - python {{PY_VER}}*
    - zlib

  run:
    - libgcc
    - python {{PY_VER}}*

about:
  home: http://www.boost.org/
  license: Boost-1.0

