package:
  name: ilastik-package
  version: "1.0.2"

build:
  number: 0

requirements:
  build:
    - git
    - ilastik-dependencies-no-solvers
    - ilastik-meta
  run:
    - git
    - ilastik-dependencies-no-solvers
    - ilastik-meta

about:
  summary: "A meta-package for creating installers."
