package:
  name: ilastik-package
  version: "1.0"

build:
  number: 1000

requirements:
  build:
    - ilastik-dependencies-no-solvers
  run:
    - ilastik-dependencies-no-solvers
    - ilastik-meta

about:
  summary: "A meta-package for creating installers."
