package:
  name: cplex-shared
  version: "0.1"
#
# No requirements!
# The first time this pacakge is installed,
# post-link.sh will create a temporary environment for gcc.
# But after that, there's no need for gcc again on subsequent installs.
#
# requirements:
#   - ###

build:
  number: 1000
  script_env:
    - CPLEX_ROOT_DIR

about:
  summary: |
    A pseudo-package that converts an existing CPLEX static libraries
    (external to your conda prefix) into shared libraries sitable for linking by other programs.
    This package does NOT install CPLEX.  You must install CPLEX externally,
    and set the CPLEX_ROOT_DIR environment variable before installing this package.
    (This package does its work at install time, not build time.)
