about:
  summary: "A meta-package for building all the dependencies needed for the minimal, headless version of pixel/object classification."

package:
  name: ilastik-deps-pc-headless
  version: "1.1"

build:
  number: 6

requirements:
  run:
    - python
    - numpy
    - vigra
    - tifffile
    - h5py
    - psutil
    - greenlet
    - yapsy
    - scikit-learn
    - scikit-image
    - jsonschema
    - nose
    #- blist # only needed by deprecated operators
    
